name: Release
on:
  push:
    branches: [ main ]
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: false
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          # Optional: If you have multiple packages or want config, use a config file
          # config-file: .release-please-config.json
